# Generated by Django 5.0 on 2024-01-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_login_info_options_alter_login_info_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login_info',
            options={},
        ),
        migrations.AlterModelManagers(
            name='login_info',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='login_info',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='login_info',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
