# Generated by Django 5.0 on 2024-02-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_login_info_options_alter_login_info_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dp', models.ImageField(null=True, upload_to='static/user_pro')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
    ]
