# Generated by Django 5.0 on 2024-02-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_user_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='dp',
            field=models.ImageField(default='static/user.png', upload_to='static/user_pro/%y'),
        ),
    ]
