# Generated by Django 5.0 on 2024-02-15 13:42

import django.db.models.deletion
import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_user_profile_dp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='dp',
        ),
        migrations.CreateModel(
            name='User_profile_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.ImageField(blank=True, null=True, upload_to=my_app.models.filepath)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
    ]
