# Generated by Django 5.0 on 2024-02-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_user_profile_dp_user_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='filepath')),
                ('like_cnt', models.IntegerField()),
                ('captions', models.CharField(max_length=200)),
                ('user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile')),
            ],
        ),
    ]
