# Generated by Django 5.0 on 2024-02-20 13:16

import django.db.models.deletion
import my_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=my_app.models.filepath1),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile')),
                ('followed_user_pro_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile_img')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following_user_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile')),
                ('following_user_pro_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile_img')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
        migrations.CreateModel(
            name='Friend_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile')),
                ('sender_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.user_profile_img')),
            ],
        ),
        migrations.CreateModel(
            name='User_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_cnt', models.IntegerField()),
                ('follower_cnt', models.IntegerField()),
                ('following_cnt', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
    ]
