# Generated by Django 5.0 on 2024-03-24 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_post1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.post1')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.login_info')),
            ],
        ),
    ]
